# Generated by Django 3.1.1 on 2021-07-13 21:38

from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_number', models.CharField(db_index=True, default=transaction.models.GenerateTransactionNumber, max_length=100, unique=True)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CLOSE', 'Close')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=60, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('required_on_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('METER', 'Meter')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('transaction_number', models.ForeignKey(db_column='transaction_number', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transaction.transaction', to_field='transaction_number')),
            ],
            options={
                'unique_together': {('transaction_number', 'article', 'color')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('METER', 'Meter')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='transaction.lineitem')),
            ],
        ),
    ]
